function fig = plotJaccard(orderedFeature, modelNames, title, options)
arguments
    orderedFeature 
    modelNames 
    title 
    options.visiblePlot ="on"
end
    JaccDistance = 1 - squareform(pdist(orderedFeature','jaccard'));
    fig = plotClustergram(JaccDistance,...
                                                                     modelNames,...
                                                                     modelNames,...
                                                                     title,...
                                                                     "Jaccard similarity",...
                                                                     [255 255 255;255 204 204;...
                                                                      255 153 153; 255 102 102; ...
                                                                      255 51 51;255 0 0; 204 0 0; ...
                                                                      152 0 0; 102 0 0;  51 0 0]/255);

    set(fig,'Visible',options.visiblePlot)

end